["wetsuit"] = {
    ["name"] = "wetsuit",
    ["label"] = "Wetsuit",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "wetsuit.png",
    ["unique"] = false,
    ["useable"] = true,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["gold"] = {
    ["name"] = "gold",
    ["label"] = "Gold Bar",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},
["diamond"] = {
    ["name"] = "diamond",
    ["label"] = "Diamond Box",
    ["weight"] = 200,
    ["type"] = "item",
    ["image"] = "blowtorch.png",
    ["unique"] = false,
    ["useable"] = false,
    ["shouldClose"] = false,
    ["combinable"] = nil,
    ["description"] = "0x0x"
},